package com.example.administrator.electronicproject;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.electronicproject.Products;

import com.example.administrator.electronicproject.ProductsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class ProductdbDaoSession extends AbstractDaoSession {

    private final DaoConfig productsDaoConfig;

    private final ProductsDao productsDao;

    public ProductdbDaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productsDaoConfig = daoConfigMap.get(ProductsDao.class).clone();
        productsDaoConfig.initIdentityScope(type);

        productsDao = new ProductsDao(productsDaoConfig, this);

        registerDao(Products.class, productsDao);
    }
    
    public void clear() {
        productsDaoConfig.clearIdentityScope();
    }

    public ProductsDao getProductsDao() {
        return productsDao;
    }

}
