package com.example.administrator.electronicproject;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "PRODUCTS".
 */
@Entity(schema = "productdb")
public class Products {

    @Id(autoincrement = true)
    private Long id;
    private String productName;
    private String productTitle;
    private String productImgUrl;
    private String productPrice;
    private String productId;

    @Generated
    public Products() {
    }

    public Products(Long id) {
        this.id = id;
    }

    @Generated
    public Products(Long id, String productName, String productTitle, String productImgUrl, String productPrice, String productId) {
        this.id = id;
        this.productName = productName;
        this.productTitle = productTitle;
        this.productImgUrl = productImgUrl;
        this.productPrice = productPrice;
        this.productId = productId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProductTitle() {
        return productTitle;
    }

    public void setProductTitle(String productTitle) {
        this.productTitle = productTitle;
    }

    public String getProductImgUrl() {
        return productImgUrl;
    }

    public void setProductImgUrl(String productImgUrl) {
        this.productImgUrl = productImgUrl;
    }

    public String getProductPrice() {
        return productPrice;
    }

    public void setProductPrice(String productPrice) {
        this.productPrice = productPrice;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

}
