package addressdao.com.example.administrator.electronicproject;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "ADDRESS".
 */
@Entity(schema = "addressdb")
public class Address {

    @Id(autoincrement = true)
    private Long id;
    private String userName;
    private String userMobile;
    private String userAddress;
    private String addressDetails;

    @Generated
    public Address() {
    }

    public Address(Long id) {
        this.id = id;
    }

    @Generated
    public Address(Long id, String userName, String userMobile, String userAddress, String addressDetails) {
        this.id = id;
        this.userName = userName;
        this.userMobile = userMobile;
        this.userAddress = userAddress;
        this.addressDetails = addressDetails;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserMobile() {
        return userMobile;
    }

    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }

    public String getUserAddress() {
        return userAddress;
    }

    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    public String getAddressDetails() {
        return addressDetails;
    }

    public void setAddressDetails(String addressDetails) {
        this.addressDetails = addressDetails;
    }

}
