package attention.com.example.administrator.electronicproject;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "ATTENTION".
 */
@Entity(schema = "attentiondb")
public class Attention {

    @Id(autoincrement = true)
    private Long id;

    @Unique
    private Integer userId;
    private String userImage;
    private String userName;
    private String userWork;

    @Generated
    public Attention() {
    }

    public Attention(Long id) {
        this.id = id;
    }

    @Generated
    public Attention(Long id, Integer userId, String userImage, String userName, String userWork) {
        this.id = id;
        this.userId = userId;
        this.userImage = userImage;
        this.userName = userName;
        this.userWork = userWork;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserImage() {
        return userImage;
    }

    public void setUserImage(String userImage) {
        this.userImage = userImage;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserWork() {
        return userWork;
    }

    public void setUserWork(String userWork) {
        this.userWork = userWork;
    }

}
