package attention.com.example.administrator.electronicproject;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attentionDaoConfig;

    private final AttentionDao attentionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attentionDaoConfig = daoConfigMap.get(AttentionDao.class).clone();
        attentionDaoConfig.initIdentityScope(type);

        attentionDao = new AttentionDao(attentionDaoConfig, this);

        registerDao(Attention.class, attentionDao);
    }
    
    public void clear() {
        attentionDaoConfig.clearIdentityScope();
    }

    public AttentionDao getAttentionDao() {
        return attentionDao;
    }

}
