package user.com.example.administrator.electronicproject;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "USER".
 */
@Entity(schema = "userdb")
public class User {

    @Id(autoincrement = true)
    private Long id;

    @Unique
    private String userNick;
    private String userSex;
    private String userId;
    private String userBirthday;
    private String userPhone;
    private String userEmail;
    private String userAddre;
    private String userImage;

    @Generated
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Generated
    public User(Long id, String userNick, String userSex, String userId, String userBirthday, String userPhone, String userEmail, String userAddre, String userImage) {
        this.id = id;
        this.userNick = userNick;
        this.userSex = userSex;
        this.userId = userId;
        this.userBirthday = userBirthday;
        this.userPhone = userPhone;
        this.userEmail = userEmail;
        this.userAddre = userAddre;
        this.userImage = userImage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserNick() {
        return userNick;
    }

    public void setUserNick(String userNick) {
        this.userNick = userNick;
    }

    public String getUserSex() {
        return userSex;
    }

    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserBirthday() {
        return userBirthday;
    }

    public void setUserBirthday(String userBirthday) {
        this.userBirthday = userBirthday;
    }

    public String getUserPhone() {
        return userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserAddre() {
        return userAddre;
    }

    public void setUserAddre(String userAddre) {
        this.userAddre = userAddre;
    }

    public String getUserImage() {
        return userImage;
    }

    public void setUserImage(String userImage) {
        this.userImage = userImage;
    }

}
